URLS = [
    # waggons
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/toyota/prius/23650474",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/toyota/corolla/23795207",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/subaru/forester/24453018",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/mitsubishi/outlander/24481414",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/toyota/sienta/23650540",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/toyota/prius/24467338",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/nissan/juke/24456681",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/bmw/x1/24509392",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/bmw/x3/24457824",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/volkswagen/passat/24432483",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/subaru/legacy/24483034",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/nissan/x-trail/24515955",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/ford/mondeo/24467761",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/mazda/5/24478192",

    # utility
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/holden/colorado/23837563",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/mitsubishi/triton/23860228",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/holden/rodeo-4x4/24444793",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/mazda/bt-50/24413708",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/toyota/hilux/23786106",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/ssangyong/actyon-sport/24450425",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/mazda/bt-50/24461715",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/mitsubishi/triton/24427675",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/ssangyong/actyon-sport/24455260",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/holden/colorado/24450879",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/ford/ranger/24490072",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/holden/colorado/24453002",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/mazda/bt-50/24462398",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/toyota/hilux/24496649",

    # hatchback
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/audi/a3/23625602",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/mazda/axela/23899730",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/toyota/sienta/24448903",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/volvo/v40/24485456",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/lexus/ct200h/23842244",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/nissan/note/24390765",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/honda/fit/23899851",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/lexus/ct200h/23625233",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/suzuki/baleno/23847671",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/honda/insight/24390945",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/suzuki/swift/24495669",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/suzuki/swift/24454238",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/mazda/demio/23603679",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/holden/cruze/24407937",

    # vans
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/nissan/serena/23567042",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/volkswagen/t5/24424706",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/toyota/hiace/24403825",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/volkswagen/t5/24437691",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/opel/vivaro/24393192",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/toyota/regius/23887023",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/hyundai/iload/24481240",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/nissan/nv350/23875730",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/toyota/hiace/23842484",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/nissan/nv350/23842568",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/toyota/hiace/24476140",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/toyota/hiace/23775291",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/nissan/nv350/23875748",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/toyota/hiace/25127014",

    # sedan
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/subaru/legacy/24508952",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/toyota/sai/19302734",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/holden/astra/24444985",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/toyota/camry/23590511",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/mercedes-benz/a-class/24439849",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/toyota/corolla/24432408",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/mercedes-benz/a-class/24415394",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/holden/commodore/24461198",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/honda/grace/24480890",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/mercedes-benz/s-class/23910028",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/honda/accord/24448620",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/toyota/camry/24481134",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/holden/commodore/24482980",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/bmw/3-series/24392201",

    # Agriculture
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/bomford-turner/vm1600/21632931",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/massey-ferguson/165/10659983",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/kverneland/9590-c-hydro/21603104",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/daedong/ck20/23095703",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/lely/900-mc/18820654",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/same/explorer-95/23516103",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/ryan/mataway-walk-behind/23826796",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/new-holland/t6020-plus/23641722",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/case/maxxum/23039158",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/john-deere/6630/22580229",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/new-holland/t5.115/24465383",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/fiat/70-66/22580737",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/walker/d21d/22539895",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/john-deere/2653a/22490865",

    # Trucks
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/hino/fs-1klkd/22972841",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/hino/500/22999993",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/mitsubishi/fighter/22610316",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/ford/transit/23039056",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/isuzu/forward/23917463",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/freightliner/argosy/24392613",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/scania/124c/20023993",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/volvo/fm/20024004",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/freightliner/frl-argosy/22999940",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/hino/300/23039039",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/isuzu/exy/20024015",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/freightliner/columbia/20133138",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/scania/124-la6x4/20132182",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/mitsubishi-fuso/shogun/20132195",

]
