URLS = [
    # waggons
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/toyota/prius/23650474",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/audi/q7/23927860",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/subaru/forester/24453018",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/subaru/forester/24439780",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/honda/jade/23650488",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/toyota/sienta/24401014",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/mitsubishi/outlander/24481414",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/toyota/sienta/23650540",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/nissan/juke/24456681",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/bmw/x1/24509392",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/bmw/x3/24457824",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/volkswagen/passat/24432483",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/toyota/prius/23775121",

    # utility
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/holden/colorado/23837563",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/foton/tunland/24491722",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/mitsubishi/triton/23860228",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/holden/rodeo-4x4/24444793",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/mazda/bt-50/24413708",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/ford/ranger/24471651",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/ford/courier/24480667",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/toyota/hilux/23786106",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/nissan/navara/23919439",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/ssangyong/actyon-sport/24450425",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/mazda/bt-50/24461715",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/mitsubishi/triton/24427675",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/ssangyong/actyon-sport/24455260",

    # hatchback
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/honda/vezel/23650403",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/audi/a3/23625602",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/mazda/axela/23899730",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/toyota/sienta/24448903",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/nissan/cube/24406118",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/volvo/v40/24485456",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/nissan/march/24401668",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/lexus/ct200h/23842244",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/nissan/note/24390765",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/honda/fit/23899851",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/lexus/ct200h/23625233",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/suzuki/baleno/23847671",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/honda/insight/24390945",

    # vans
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/nissan/serena/23567042",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/volkswagen/t5/24424706",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/toyota/hiace/24403825",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/volkswagen/t5/24437691",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/opel/vivaro/24393192",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/toyota/regius/23887023",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/hyundai/iload/24481240",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/ford/transit/24481181",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/toyota/hiace/23895476",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/nissan/nv350/23875730",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/toyota/hiace/23566198",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/toyota/hiace/24395165",
    "https://www.turners.co.nz/Cars/Used-Cars-for-Sale/nissan/nv350/23842568",

    # Agriculture
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/kubota/b2150-hsd/23038112",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/john-deere/x540/22581114",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/bomford-turner/vm1600/21632931",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/trimax/front-mower/20101737",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/massey-ferguson/165/10659983",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/kverneland/9590-c-hydro/21603104",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/daedong/ck20/23095703",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/lely/900-mc/18820654",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/same/explorer-95/23516103",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/ryan/mataway-walk-behind/23826796",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/new-holland/t6020-plus/23641722",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/case/maxxum/23039158",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/john-deere/6630/22580229",

    # Trucks
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/mitsubishi/fv/18691795",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/fuso/canter-516/22971157",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/iveco/acco/22971161",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/isuzu/npr/25490169",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/hino/ranger/24263497",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/mitsubishi-fuso/canter/17295353",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/isuzu/forward/22490733",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/nissan/ud/23039416",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/hino/dutro/22511820",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/isuzu/elf/21621500",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/isuzu/forward/22490906",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/isuzu/n-series/21621537",
    "https://www.turners.co.nz/Trucks-Machinery/Used-Trucks-and-Machinery-for-Sale/nissan/diesel/24263484",

]
